version: 2
jobs:
  build:
    working_directory: /go/src/github.com/testcontainers/testcontainer-go
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          keys:
            - gomod-cache-{{ checksum "go.sum" }}
      - run:
          name: Check fmt format
          command: GO111MODULE=on go fmt ./...
      - run:
          name: Check vet
          command: GO111MODULE=on go vet ./...
      - run:
          name: Check tests
          command: GO111MODULE=on go test ./...
      - save_cache:
          key: gomod-cache-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod
