version: 2
executorType: machine
jobs:
  build:
    steps:
      - run:
          command: mkdir gov
      - run:
          command: cd gov & wget https://dl.google.com/go/go1.11.linux-amd64.tar.gz
      - run:
          command: cd gov & tar -xvf go1.11.linux-amd64.tar.gz
      - checkout
      - run:
          name: go check
          command: gov/go/bin/go version
      - run:
          name: verify modules
          command: GO111MODULE=on gov/go/bin/go mod verify
      - run:
          name: Check fmt format
          command: GO111MODULE=on gov/go/bin/go fmt ./...
      - run:
          name: Check vet
          command: GO111MODULE=on gov/go/bin/go vet ./...
      - run:
          name: Check tests
          command: GO111MODULE=on gov/go/bin/go test ./...
